# Generated by Django 3.0.8 on 2020-08-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('K1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLS',
            new_name='URLS1',
        ),
    ]
