# Generated by Django 3.0.8 on 2020-08-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('K1', '0002_auto_20200811_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URLS1',
            new_name='Links',
        ),
    ]
