# Generated by Django 3.0.8 on 2020-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('K1', '0004_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sectionNo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
