# Generated by Django 3.0.8 on 2020-08-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('K1', '0005_test_sectionno'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='decription',
            field=models.TextField(null=True),
        ),
    ]
